services:
  eewrendererstg:
    image: ghcr.io/eewbot/eew-renderer:dev@sha256:31e2fb80255b577b5c3fac05a925e8d984706e01184ccb2fc22b04e1c1d3f343
    hostname: eewrenderer
    container_name: eewrendererstg${VARIANT:-}__eewrendererstg
    restart: unless-stopped

    environment:
      LISTEN: 0.0.0.0:3000
      ALLOW_DEMO: ${ALLOW_DEMO:-false}
      HMAC_KEY: ${HMAC_KEY}
      INSTANCE_NAME: ${INSTANCE_NAME}
      MINIMUM_RESPONSE_INTERVAL: ${MINIMUM_RESPONSE_INTERVAL}
      HEADLESS: true
      IMAGE_CACHE_CAPACITY: ${IMAGE_CACHE_CAPACITY:-512}

    command: /usr/bin/eew-renderer

    deploy:
      resources:
        limits:
          memory: 2g

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.8.2
    hostname: cloudflared
    container_name: eewrendererstg${VARIANT:-}__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: eewrendererstg${VARIANT:-}__default
