services:
  eewrendererstg:
    image: ghcr.io/eewbot/eew-renderer:dev@sha256:e6426a2294339da2e0d6221957830a7d6c525931b35c8820352775a861d17a6d
    hostname: eewrenderer
    container_name: eewrendererstg${VARIANT:-}__eewrendererstg
    restart: unless-stopped

    environment:
      LISTEN: 0.0.0.0:3000
      HMAC_KEY: ${HMAC_KEY}
      INSTANCE_NAME: ${INSTANCE_NAME}
      MINIMUM_RESPONSE_INTERVAL: ${MINIMUM_RESPONSE_INTERVAL:-200ms}
      IMAGE_CACHE_CAPACITY: ${IMAGE_CACHE_CAPACITY:-512}
      EGL_DEVICE_INDEX: ${EGL_DEVICE_INDEX:-0}

    command: /usr/bin/eew-renderer

    devices:
      - /dev/dri:/dev/dri

    deploy:
      resources:
        limits:
          memory: 2g

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.9.3
    hostname: cloudflared
    container_name: eewrendererstg${VARIANT:-}__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: eewrendererstg${VARIANT:-}__default
