services:
  eewrendererstg:
    image: ghcr.io/eewbot/eew-renderer:dev@sha256:816a3c3b22589c47f4ee0477730b8fa5133da06f42ad15a6020cf68abb17e5bc
    hostname: eewrenderer
    container_name: eewrendererstg${VARIANT:-}__eewrendererstg
    restart: unless-stopped

    environment:
      LISTEN: 0.0.0.0:3000
      ALLOW_DEMO: ${ALLOW_DEMO:-false}
      HMAC_KEY: ${HMAC_KEY}
      INSTANCE_NAME: ${INSTANCE_NAME}
      MINIMUM_RESPONSE_INTERVAL: ${MINIMUM_RESPONSE_INTERVAL:-200ms}
      HEADLESS: true
      IMAGE_CACHE_CAPACITY: ${IMAGE_CACHE_CAPACITY:-512}
      EGL_DEVICE_INDEX: ${EGL_DEVICE_INDEX:-0}

    command: /usr/bin/eew-renderer

    devices:
      - /dev/dri:/dev/dri

    deploy:
      resources:
        limits:
          memory: 2g

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.7.3
    hostname: cloudflared
    container_name: eewrendererstg${VARIANT:-}__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: eewrendererstg${VARIANT:-}__default
