services:
  eewrendererstg:
    image: ghcr.io/eewbot/eew-renderer:master@sha256:4124481b9487c1d8e7803f04e7876057f3ea866c7a502169d8b60554dd937b2c
    hostname: eewrenderer
    container_name: eewrendererstg${VARIANT:-}__eewrendererstg
    restart: unless-stopped

    environment:
      LISTEN: 0.0.0.0:3000
      DISPLAY: ${DISPLAY}
      ALLOW_DEMO: ${ALLOW_DEMO}
      HMAC_KEY: ${HMAC_KEY}
      INSTANCE_NAME: ${INSTANCE_NAME}
      MINIMUM_RESPONSE_INTERVAL: ${MINIMUM_RESPONSE_INTERVAL}

    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix

    command: /usr/bin/eew-renderer

    devices:
      - /dev/dri:/dev/dri

    deploy:
      resources:
        limits:
          memory: 2g

    networks:
      - default

  cloudflared:
    image: cloudflare/cloudflared:2026.7.2
    hostname: cloudflared
    container_name: eewrendererstg${VARIANT:-}__cloudflared

    restart: unless-stopped

    environment:
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}
    user: root

    deploy:
      resources:
        limits:
          memory: 128m

    networks:
      - default

networks:
  default:
    name: eewrendererstg${VARIANT:-}__default
